In [1]:
import numpy as np

In [9]:
#creating 0d array- scalar array

a = np.array(4)

a

array(4)

In [16]:
#creating 1d array- scalar array

a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [17]:
type(a)

numpy.ndarray

In [18]:
#Dimension of array

a.ndim

1

In [20]:
#creating 2d array

b = np.array([[1,2,3],[4,5,6]],dtype=float)

print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [21]:
b.ndim

2

In [24]:
#creating 3d array

c = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],dtype=float)

print(c)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


In [26]:
#Dimension of 3d array
c.ndim

3

In [32]:
#Defining number of dimensions 

x = np.array([1,2,3,4],ndmin=4)

print(x)

[[[[1 2 3 4]]]]


In [33]:
#creating a array of zeros

y = np.zeros((4,2))

print(y)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [35]:
#creating a array of ones

z = np.ones((2,4))

print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
#Eye Function:   Returns array filled with zeros except in the kth diagonal, whose values are equal to 1

a = np.eye(5)

print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [38]:
a = np.eye(2,3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]]


In [41]:
a = np.eye(4,k=-1)

print(a)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [45]:
a=np.eye(5,k=1)

print(a)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [48]:
a = np.eye(5,dtype=int)

print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# Accessing Array Elements

In [51]:
# Accessing 1 d array

a = np.array([1,2,3,4])

print(a[0])

print(a[2])

print(a[1] + a[3])

1
3
6


In [54]:
#Access 2-D Arrays

b = np.array([[1,2,3],[4,5,6]])

print(b[1,2])

print(b[0,2])

print(b[1,0])

6
3
4


In [55]:
#Access 3-D Arrays

c = np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])

print(c[1,1,1])

print(c[1,0,1])

print(c[0,0,1])

11
8
2


In [57]:
#Negative Indexing

a = np.array([[1,2,3],[4,5,6]])

print(a[1,-1])

print(a[0,-1])

print(a[-1,0])

6
3
4


# Slicing Array

In [58]:
a = np.array([1,2,3,4,5,6,7])

print(a[0:3])

print(a[2:])

print(a[:5])

print(a[-4:-1])

print(a[1:5:2])

print(a[::3])

[1 2 3]
[3 4 5 6 7]
[1 2 3 4 5]
[4 5 6]
[2 4]
[1 4 7]


In [62]:
#Slicing 2-D Arrays

a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(a[1,1:4])

print(a[0,1:4])

print(a[1,::2])

print(a[1,2:-1])

[7 8 9]
[2 3 4]
[ 6  8 10]
[8 9]


# Finding dtype of Array

In [63]:
a = np.array([1, 2, 3, 4])

print(a.dtype)

int32


In [64]:
#Create an array with data type string

a=np.array([1, 2, 3, 4], dtype='S')

print(a.dtype)

|S1


In [65]:
#Change data type from float to integer by using int as parameter value

a = np.array([1.1, 2.2, 3.3, 4.3])

b = a.astype(int)

print(b.dtype)

print(b)

c = a.astype(bool)

print(c.dtype)

print(c)

int32
[1 2 3 4]
bool
[ True  True  True  True]


In [68]:
#copy to the arra

x = np.array([1,2,3,4])

y = np.copy(x)

x[0] = 6

print(x)

print(y)

[6 2 3 4]
[1 2 3 4]


In [69]:
#view is just a view of the original array

x = np.array([1, 2, 3, 4, 5])

y = x.view()

x[0] = 42

print(x)

print(y)

[42  2  3  4  5]
[42  2  3  4  5]


# shape of an Array

In [71]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(a)

print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


# Reshaping the Array

In [74]:
#Reshape From 1-D to 2-D
a= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(a)

print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [77]:
b = a.reshape(3,4)

print(b)

print(b.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [81]:
#Reshape From 1-D to 2-D

c = a.reshape(2,2,3)

print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Flattening the arrays

# Flattening array means converting a multidimensional array into a 1D array

In [82]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.reshape(-1)

print(b)

[1 2 3 4 5 6]


# Iterating Arrays

# Iterating means going through elements one by one.

In [83]:
#Iterating 1-D Arrays

a = np.array([1, 2, 3])

for i in a:

    print(i)

1
2
3


In [86]:
#Iterating 2-D Arrays

a = np.array([[1, 2, 3],[4,5,6]])

for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6


In [87]:
#Iterating 3-D Arrays

a = np.array([[[1, 2, 3],[4,5,6]],[[7,8,9],[10,11,12]]])

for i in a:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [90]:
#Iterating -D Arrays using nditer 

a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for i in np.nditer(a):
    
    print(i)

1
2
3
4
5
6
7
8


In [91]:
#Iterate through every scalar element of the 2D array skipping 1 element

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for i in np.nditer(a[0,::]):
    print(i)

1
2
3
4


In [94]:
for i in np.nditer(a[1,::2]):
    
    print(i)

5
7


In [97]:
#Enumerate  1D arrays

x = np.array([1, 2, 3])

for i in np.ndenumerate(x):
    print(i)

((0,), 1)
((1,), 2)
((2,), 3)


In [98]:
for index,i in np.ndenumerate(x):
    print(index,i)

(0,) 1
(1,) 2
(2,) 3


In [99]:
#Enumerate 2D array

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for index,i in np.ndenumerate(x):

    print(index, i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining NumPy Arrays

# Merging elements of two or more arrays in a single array.

In [100]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = np.concatenate((a,b))

print(c)

[1 2 3 4 5 6]


In [103]:
a = np.array([[1, 2],[3,4]])

b = np.array([[5, 6],[7,8]])

c = np.concatenate((a,b),axis=1)

print(c)

[[1 2 5 6]
 [3 4 7 8]]


# Stacking Arrays

# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [116]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = np.stack((a,b),axis=1)

print(c)

[[1 4]
 [2 5]
 [3 6]]


In [121]:
#Stacking Along Rows

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = np.hstack((a,b))

print(c)

[1 2 3 4 5 6]


In [122]:
#Stacking Along columns

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = np.vstack((a,b))

print(c)

[[1 2 3]
 [4 5 6]]


In [123]:
#axis is not #it is also along columns #np.vstack()

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = np.stack((a,b))

print(c)

[[1 2 3]
 [4 5 6]]


In [124]:
#Stacking Along Height/Depth

a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = np.dstack((a,b))
print(c)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting NumPy Arrays

# It is the reverse operation of Joining

# Splits single array into multiple

In [128]:
a = np.array([1, 2, 3, 4, 5, 6])

b = np.array_split(a, 8) #If it has les elements it will create blank arrays


print(b)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32)]


In [130]:
print(b[0])

print(b[1])

print(b[7])

[1]
[2]
[]


In [132]:
#Split the 2-D array 

a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

b= np.array_split(a,3)

print(b)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [133]:
b= np.array_split(a,4)

print(b)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]


In [134]:
#Split the 2-D array along rows

a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

a1= np.array_split(a,4,axis=1)

print(a1)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]]), array([], shape=(6, 0), dtype=int32)]


In [136]:
#Split the 2-D array along rows

a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

b= np.hsplit(a,3)

print(b)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Searching Arrays

In [137]:
x = np.array([1, 2, 3, 4, 5, 4, 4])

#element 4 is in the three index positions 

v = np.where(x==4)

print(v)

(array([3, 5, 6], dtype=int64),)


In [138]:
#Finding the elements in even indices

x = np.array([1, 2, 3, 4, 5, 4, 4])

#Displays the elements in the index position 

v = np.where(x %2 == 0)

print(v)

(array([1, 3, 5, 6], dtype=int64),)


In [139]:
#Finding the elements in even indices

x = np.array([1, 2, 3, 4, 5, 4, 4])

#Displays the elements in the index position 

v = np.where(x %2 == 1)

print(v)

(array([0, 2, 4], dtype=int64),)


In [142]:
#search the element and returns the index

a = np.array([1,2,3,4])

x = np.searchsorted(a, 4)

print(x)

3


In [149]:
#search the element and returns the index if search number is not there = no of index + 1 *index start from 0

b = np.array([1,2,3,4,5])

v = np.searchsorted(b, 7)

print(v)



5


# Sorting Array

In [150]:
a= np.array([56,34,89,93,12])

print(np.sort(a))

[12 34 56 89 93]


In [151]:
#strings are sorted alphabetically

a = np.array(['python', 'datascience', 'artificial intelligence','machine learning'])

print(np.sort(a))

['artificial intelligence' 'datascience' 'machine learning' 'python']


In [152]:
#booleans are sorted false as first

a = np.array([True, False, True])

print(np.sort(a))

[False  True  True]


In [153]:
#Sort a 2-D array

a = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(a))

[[2 3 4]
 [0 1 5]]


# LINEAR ALGEBRA

# Dot product of the two arrays

In [154]:
x = np.array([[1,2],[3,4]]) 

y = np.array([[5,6],[7,8]]) 

np.dot(x,y)

array([[19, 22],
       [43, 50]])

# Dot product of the two vectors

In [155]:
x = np.array([[1,2],[3,4]]) 

y = np.array([[5,6],[7,8]]) 

np.vdot(x,y)

70

In [156]:
x = np.array([[1,2], [3,4]]) 

print(x)

y = np.array([[11, 12], [13, 14]]) 

print(y)

print ('Inner product:' )

print (np.inner(x,y))

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
Inner product:
[[35 41]
 [81 95]]


# Inverse of matrix

In [158]:
x = np.array([[1,2],[3,4]])

y = np.linalg.inv(x)

print(y)

[[-2.   1. ]
 [ 1.5 -0.5]]


# Determinant of Matrix

In [159]:
# Determinant  [[a,b], [c,d]], = ‘ad-bc’

a=np.array([[1,2],[3,4]])

np.linalg.det(a)

-2.0000000000000004

In [160]:
round(np.linalg.det(a))

-2

In [161]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

np.linalg.det(b)

6.66133814775094e-16

In [162]:
round(np.linalg.det(b))

0

# Solve Linear Equation Using NumPy

In [164]:
a= np.array([[3,1],[1,2]])

b=np.array([9,8])

np.linalg.solve(a,b)

array([2., 3.])

# Statistical Functions

In [165]:
#finding the minimum and maximum value in the array

a= np.array([[3,1],[1,2]])

print(np.amax(a))

print(np.amin(a))

3
1


In [166]:
# Mean - sum of the elements divided by no of elements

a = np.array([1,2,3,4])

print(np.mean(a))

2.5


In [167]:
# Median - middle element if no of elements are even

a = np.array([1,2,3,4])

print(np.median(a))

2.5


In [168]:
# Median - middle element if no of elements are odd

a = np.array([1,2,3])

print(np.median(a))

2.0


In [169]:
#standard Deviations 1. calculate the mean 2. std deviation

a = np.array([1,2,3,4])

print(a)

print(np.std(a))

[1 2 3 4]
1.118033988749895


In [170]:
#variance

a = np.array([1,2,3,4])

print(a)

print(np.var(a))

[1 2 3 4]
1.25
